version: "3.8"

networks:
  splunk-network:
    driver: bridge
  splunk-ai-network:
    external: true
    name: deslicer-splunk-ai-sidekick_splunk-ai-network

services:
  # Splunk Enterprise
  so1:
    networks:
      splunk-network:
        aliases:
          - so1
      splunk-ai-network:
        aliases:
          - so1-splunk
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    platform: linux/amd64
    hostname: so1
    container_name: so1
    restart: unless-stopped
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=26898dec-83d1-49f1-b06e-90eabff7f543
      - SPLUNK_PASSWORD=Chang3d!
    ports:
      - "9000:8000"   # Splunk Web UI
      - "8088:8088"   # HEC
      - "8089:8089"   # Management port
    volumes:
      - ./lic/splunk.lic:/tmp/license/splunk.lic
    healthcheck:
      test: ["CMD", "curl", "-s", "-k", "https://localhost:8089/services/server/info"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s