name: auto-approve release-please PRs

on:
  pull_request:
    types: [opened, labeled, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Approve release-please PRs from github-actions when labeled
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          PR_NUMBER='${{ github.event.pull_request.number }}'
          REPO='${{ github.repository }}'
          if [ -z "$PR_NUMBER" ]; then
            echo "Not a pull_request event; skipping"
            exit 0
          fi
          author=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json author -q .author.login)
          echo "author=$author"
          if [ "$author" != "github-actions[bot]" ]; then
            echo "Not a release-please PR author; skipping"
            exit 0
          fi
          if ! gh pr view "$PR_NUMBER" --repo "$REPO" --json labels -q '.labels[].name' | grep -Fx "autorelease: pending" >/dev/null; then
            echo "Label 'autorelease: pending' not present; skipping"
            exit 0
          fi
          echo "Approving PR #$PR_NUMBER"
          gh pr review "$PR_NUMBER" --repo "$REPO" --approve || true

