name: auto-approve release-please PRs

on:
  pull_request:
    types: [opened, labeled, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Approve release-please PRs from github-actions when labeled
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          PR_NUMBER='${{ github.event.pull_request.number }}'
          REPO='${{ github.repository }}'
          if [ -z "$PR_NUMBER" ]; then
            echo "Not a pull_request event; skipping"
            exit 0
          fi
          author=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json author -q .author.login)
          head_ref=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json headRefName -q .headRefName)
          title=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json title -q .title)
          echo "author=$author head_ref=$head_ref title=$title"
          if ! gh pr view "$PR_NUMBER" --repo "$REPO" --json labels -q '.labels[].name' | grep -Fx "autorelease: pending" >/dev/null; then
            echo "Label 'autorelease: pending' not present; skipping"
            exit 0
          fi
          # Approve if it's a release-please PR by bot OR the release-please branch pattern OR standard release title
          if [ "$author" = "github-actions[bot]" ] || echo "$head_ref" | grep -q '^release-please--branches--' || echo "$title" | grep -q '^chore\(main\): release '; then
            echo "Approving PR #$PR_NUMBER"
            gh pr review "$PR_NUMBER" --repo "$REPO" --approve || true
          else
            echo "PR does not match release-please criteria; skipping approval"
          fi

