name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python 3.10 via uv
        run: uv python install 3.10

      - name: Sync dependencies (dev)
        run: uv sync --dev

      - name: Lint (ruff)
        run: uv run ruff check src/

      - name: Type check (mypy)
        run: uv run mypy src/

      - name: Run tests
        env:
          PYTHONUNBUFFERED: "1"
        run: uv run pytest -q --maxfail=1


