name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,test]

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Type check (mypy)
        run: |
          mypy .

      - name: Run tests
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          pytest -q --maxfail=1


